### ISSUE TITLE
Add CI testing environment in Mac for install workflow

### ISSUE THREAD

**Issue by gsheni** [alteryx/evalml#3415]
- We should modify the Install Test workflow that install EvalML in MacOS and Ubuntu (currently its only Ubuntu):
```yaml
name: Install Test
jobs:
  install_ft_complete:
    name: ${{ matrix.os }} - ${{ matrix.python_version }} install evalml
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        python_version: ["3.8", "3.9", "3.10"]
```
